import numpy as np
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import sys

# Read in MFCC csv files generated by Yaafe
files = sys.argv[1:]

points = []
current = 0
for file in files:
    # read the csv file
    raw_data = np.genfromtxt(file, skip_header = 5, delimiter = ",")
    print raw_data
    nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(raw_data[:1])
    dist, indices = nbrs.kneighbors(raw_data[:1])
    print indices
